// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package db

import (
	"context"
)

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT a.id, a.course_id, a.author_id, a.title, a.body, a.audience_type, a.created_at
FROM announcements a
JOIN courses c ON a.course_id = c.id
WHERE a.id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id int64) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.AudienceType,
		&i.CreatedAt,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
INSERT INTO announcements (course_id, author_id, title, body, audience_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, author_id, title, body, audience_type, created_at
`

type InsertAnnouncementParams struct {
	CourseID     int64
	AuthorID     int64
	Title        string
	Body         string
	AudienceType string
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.CourseID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.AudienceType,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.AudienceType,
		&i.CreatedAt,
	)
	return i, err
}

const insertAnnouncementRecipient = `-- name: InsertAnnouncementRecipient :exec
INSERT INTO announcement_recipients (announcement_id, student_id)
VALUES ($1, $2)
`

type InsertAnnouncementRecipientParams struct {
	AnnouncementID int64
	StudentID      int64
}

func (q *Queries) InsertAnnouncementRecipient(ctx context.Context, arg InsertAnnouncementRecipientParams) error {
	_, err := q.db.Exec(ctx, insertAnnouncementRecipient, arg.AnnouncementID, arg.StudentID)
	return err
}

const listAnnouncementRecipients = `-- name: ListAnnouncementRecipients :many
SELECT student_id
FROM announcement_recipients
WHERE announcement_id = $1
`

func (q *Queries) ListAnnouncementRecipients(ctx context.Context, announcementID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAnnouncementRecipients, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var student_id int64
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementsForStudent = `-- name: ListAnnouncementsForStudent :many
SELECT a.id, a.course_id, a.author_id, a.title, a.body, a.audience_type, a.created_at
FROM announcements a
JOIN courses c ON a.course_id = c.id
JOIN student_enrollments se ON se.course_id = a.course_id AND se.student_id = $2
LEFT JOIN announcement_recipients ar ON ar.announcement_id = a.id AND ar.student_id = $2
WHERE a.course_id = $1 AND c.deleted_at IS NULL
  AND (a.audience_type = 'ALL_STUDENTS' OR ar.student_id IS NOT NULL)
ORDER BY a.created_at DESC
`

type ListAnnouncementsForStudentParams struct {
	CourseID  int64
	StudentID int64
}

func (q *Queries) ListAnnouncementsForStudent(ctx context.Context, arg ListAnnouncementsForStudentParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsForStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.AudienceType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseAnnouncements = `-- name: ListCourseAnnouncements :many
SELECT a.id, a.course_id, a.author_id, a.title, a.body, a.audience_type, a.created_at
FROM announcements a
JOIN courses c ON a.course_id = c.id
WHERE a.course_id = $1 AND c.deleted_at IS NULL
ORDER BY a.created_at DESC
`

func (q *Queries) ListCourseAnnouncements(ctx context.Context, courseID int64) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listCourseAnnouncements, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.AudienceType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
