// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auditlogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_log
WHERE ($1::bigint IS NULL OR actor_id = $1)
  AND ($2::text   IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz   IS NULL OR created_at <= $4)
`

type CountAuditLogsParams struct {
	ActorID pgtype.Int8
	Action  pgtype.Text
	From    pgtype.Timestamptz
	To      pgtype.Timestamptz
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, target, metadata, created_at, target_type, target_id, operation_id, affected_count FROM audit_log
WHERE ($3::bigint IS NULL OR actor_id = $3)
  AND ($4::text   IS NULL OR action = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz   IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit   int32
	Offset  int32
	ActorID pgtype.Int8
	Action  pgtype.Text
	From    pgtype.Timestamptz
	To      pgtype.Timestamptz
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.Action,
		arg.From,
		arg.To,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Target,
			&i.Metadata,
			&i.CreatedAt,
			&i.TargetType,
			&i.TargetID,
			&i.OperationID,
			&i.AffectedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_log (actor_id, action, target_type, target_id, affected_count, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type WriteAuditLogParams struct {
	ActorID       pgtype.Int8
	Action        string
	TargetType    pgtype.Text
	TargetID      pgtype.Int8
	AffectedCount pgtype.Int4
	Metadata      []byte
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.AffectedCount,
		arg.Metadata,
	)
	return err
}
