// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*) FROM courses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR term = $1)
  AND ($2::text IS NULL OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
`

type CountCoursesParams struct {
	Term   pgtype.Text
	Search pgtype.Text
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, arg.Term, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (code, name, term, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, term, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateCourseParams struct {
	Code      string
	Name      string
	Term      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Code,
		arg.Name,
		arg.Term,
		arg.StartDate,
		arg.EndDate,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, code, name, term, start_date, end_date, created_at, updated_at, deleted_at FROM courses WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCourseLecturers = `-- name: ListCourseLecturers :many
SELECT u.id AS lecturer_id, u.username, u.full_name
FROM course_lecturers l
JOIN users u ON u.id = l.lecturer_id
WHERE l.course_id = $1 AND u.deleted_at IS NULL
`

type ListCourseLecturersRow struct {
	LecturerID int64
	Username   string
	FullName   pgtype.Text
}

func (q *Queries) ListCourseLecturers(ctx context.Context, courseID int64) ([]ListCourseLecturersRow, error) {
	rows, err := q.db.Query(ctx, listCourseLecturers, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseLecturersRow
	for rows.Next() {
		var i ListCourseLecturersRow
		if err := rows.Scan(&i.LecturerID, &i.Username, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseStudents = `-- name: ListCourseStudents :many
SELECT u.id AS student_id, u.username, u.full_name
FROM student_enrollments e
JOIN users u ON u.id = e.student_id
WHERE e.course_id = $1 AND u.deleted_at IS NULL
`

type ListCourseStudentsRow struct {
	StudentID int64
	Username  string
	FullName  pgtype.Text
}

func (q *Queries) ListCourseStudents(ctx context.Context, courseID int64) ([]ListCourseStudentsRow, error) {
	rows, err := q.db.Query(ctx, listCourseStudents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseStudentsRow
	for rows.Next() {
		var i ListCourseStudentsRow
		if err := rows.Scan(&i.StudentID, &i.Username, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, code, name, term, start_date, end_date, created_at, updated_at, deleted_at FROM courses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR term = $1)
  AND ($2::text IS NULL OR code ILIKE '%' || $2 || '%' OR name ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListCoursesParams struct {
	Term   pgtype.Text
	Search pgtype.Text
	Offset int32
	Limit  int32
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Term,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Term,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCourse = `-- name: SoftDeleteCourse :exec
UPDATE courses SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteCourse, id)
	return err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses SET code = $2, name = $3, term = $4, start_date = $5, end_date = $6, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, term, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateCourseParams struct {
	ID        int64
	Code      string
	Name      string
	Term      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Term,
		arg.StartDate,
		arg.EndDate,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
