// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: enrollments.sql

package db

import (
	"context"
)

const assignLecturer = `-- name: AssignLecturer :execrows
INSERT INTO course_lecturers (course_id, lecturer_id)
VALUES ($1, $2)
ON CONFLICT (course_id, lecturer_id) DO NOTHING
`

type AssignLecturerParams struct {
	CourseID   int64
	LecturerID int64
}

func (q *Queries) AssignLecturer(ctx context.Context, arg AssignLecturerParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignLecturer, arg.CourseID, arg.LecturerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enrollStudent = `-- name: EnrollStudent :execrows
INSERT INTO student_enrollments (course_id, student_id)
VALUES ($1, $2)
ON CONFLICT (course_id, student_id) DO NOTHING
`

type EnrollStudentParams struct {
	CourseID  int64
	StudentID int64
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) (int64, error) {
	result, err := q.db.Exec(ctx, enrollStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserIDsByRole = `-- name: GetUserIDsByRole :many
SELECT id, username
FROM users
WHERE username = ANY($1::text[])
  AND role = $2
  AND is_system = FALSE
  AND deleted_at IS NULL
`

type GetUserIDsByRoleParams struct {
	Column1 []string
	Role    UserRole
}

type GetUserIDsByRoleRow struct {
	ID       int64
	Username string
}

func (q *Queries) GetUserIDsByRole(ctx context.Context, arg GetUserIDsByRoleParams) ([]GetUserIDsByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUserIDsByRole, arg.Column1, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserIDsByRoleRow
	for rows.Next() {
		var i GetUserIDsByRoleRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudent = `-- name: RemoveStudent :execrows
DELETE FROM student_enrollments
WHERE course_id = $1 AND student_id = $2
`

type RemoveStudentParams struct {
	CourseID  int64
	StudentID int64
}

func (q *Queries) RemoveStudent(ctx context.Context, arg RemoveStudentParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unassignLecturer = `-- name: UnassignLecturer :execrows
DELETE FROM course_lecturers
WHERE course_id = $1 AND lecturer_id = $2
`

type UnassignLecturerParams struct {
	CourseID   int64
	LecturerID int64
}

func (q *Queries) UnassignLecturer(ctx context.Context, arg UnassignLecturerParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignLecturer, arg.CourseID, arg.LecturerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
