// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const computeAssignmentAverage = `-- name: ComputeAssignmentAverage :one
WITH eligible AS (
    SELECT a.id, a.max_score
    FROM assignments a
    JOIN courses c ON a.course_id = c.id
    WHERE a.course_id = $1 AND c.deleted_at IS NULL
      AND a.grading_finalized_at IS NOT NULL
      AND a.max_score IS NOT NULL AND a.max_score > 0
), per_assignment AS (
    SELECT e.id,
           COALESCE(
             (SELECT s.score FROM submissions s
              WHERE s.assignment_id = e.id AND s.student_id = $2
                AND s.score IS NOT NULL
              ORDER BY s.version DESC LIMIT 1),
             0) / e.max_score * 100 AS normalized
    FROM eligible e
)
SELECT COALESCE(AVG(normalized), 0)::numeric AS assignment_average,
       COUNT(*)::int AS eligible_count
FROM per_assignment
`

type ComputeAssignmentAverageParams struct {
	CourseID  int64
	StudentID int64
}

type ComputeAssignmentAverageRow struct {
	AssignmentAverage pgtype.Numeric
	EligibleCount     int32
}

func (q *Queries) ComputeAssignmentAverage(ctx context.Context, arg ComputeAssignmentAverageParams) (ComputeAssignmentAverageRow, error) {
	row := q.db.QueryRow(ctx, computeAssignmentAverage, arg.CourseID, arg.StudentID)
	var i ComputeAssignmentAverageRow
	err := row.Scan(&i.AssignmentAverage, &i.EligibleCount)
	return i, err
}

const computeQuizAverage = `-- name: ComputeQuizAverage :one
WITH eligible AS (
    SELECT q.id, q.max_grade
    FROM quizzes q
    JOIN courses c ON q.course_id = c.id
    WHERE q.course_id = $1 AND c.deleted_at IS NULL
      AND q.close_at IS NOT NULL AND q.close_at <= now()
      AND q.max_grade IS NOT NULL AND q.max_grade > 0
), per_quiz AS (
    SELECT e.id,
           COALESCE(
             (SELECT MAX(a.score) FROM quiz_attempts a
              WHERE a.quiz_id = e.id AND a.student_id = $2
                AND a.status IN ('SUBMITTED','AUTO_SUBMITTED')),
             0) / e.max_grade * 100 AS normalized
    FROM eligible e
)
SELECT COALESCE(AVG(normalized), 0)::numeric AS quiz_average,
       COUNT(*)::int AS eligible_count
FROM per_quiz
`

type ComputeQuizAverageParams struct {
	CourseID  int64
	StudentID int64
}

type ComputeQuizAverageRow struct {
	QuizAverage   pgtype.Numeric
	EligibleCount int32
}

func (q *Queries) ComputeQuizAverage(ctx context.Context, arg ComputeQuizAverageParams) (ComputeQuizAverageRow, error) {
	row := q.db.QueryRow(ctx, computeQuizAverage, arg.CourseID, arg.StudentID)
	var i ComputeQuizAverageRow
	err := row.Scan(&i.QuizAverage, &i.EligibleCount)
	return i, err
}

const countSchemePublications = `-- name: CountSchemePublications :one
SELECT COUNT(*)
FROM grade_publications p
JOIN grade_components c ON p.component_id = c.id
WHERE c.scheme_id = $1
`

func (q *Queries) CountSchemePublications(ctx context.Context, schemeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSchemePublications, schemeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSchemeScores = `-- name: CountSchemeScores :one
SELECT COUNT(*)
FROM grade_scores s
JOIN grade_components c ON s.component_id = c.id
WHERE c.scheme_id = $1
`

func (q *Queries) CountSchemeScores(ctx context.Context, schemeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSchemeScores, schemeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelComponents = `-- name: CountTopLevelComponents :one
SELECT COUNT(*)
FROM grade_components c
JOIN grade_schemes s ON c.scheme_id = s.id
WHERE s.course_id = $1 AND c.parent_id IS NULL
`

func (q *Queries) CountTopLevelComponents(ctx context.Context, courseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTopLevelComponents, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGradeScheme = `-- name: CreateGradeScheme :one
INSERT INTO grade_schemes (course_id, created_by)
VALUES ($1, $2)
RETURNING id, course_id, created_by, created_at
`

type CreateGradeSchemeParams struct {
	CourseID  int64
	CreatedBy int64
}

func (q *Queries) CreateGradeScheme(ctx context.Context, arg CreateGradeSchemeParams) (GradeScheme, error) {
	row := q.db.QueryRow(ctx, createGradeScheme, arg.CourseID, arg.CreatedBy)
	var i GradeScheme
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSchemeComponents = `-- name: DeleteSchemeComponents :exec
DELETE FROM grade_components WHERE scheme_id = $1
`

func (q *Queries) DeleteSchemeComponents(ctx context.Context, schemeID int64) error {
	_, err := q.db.Exec(ctx, deleteSchemeComponents, schemeID)
	return err
}

const deleteSchemeIfEmpty = `-- name: DeleteSchemeIfEmpty :execrows
DELETE FROM grade_schemes gs
WHERE gs.id = $1 AND gs.course_id = $2
  AND NOT EXISTS (
      SELECT 1 FROM grade_components c
      JOIN grade_scores s ON s.component_id = c.id
      WHERE c.scheme_id = gs.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM grade_components c
      JOIN grade_publications p ON p.component_id = c.id
      WHERE c.scheme_id = gs.id
  )
`

type DeleteSchemeIfEmptyParams struct {
	ID       int64
	CourseID int64
}

func (q *Queries) DeleteSchemeIfEmpty(ctx context.Context, arg DeleteSchemeIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchemeIfEmpty, arg.ID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchemeByCourse = `-- name: GetSchemeByCourse :one
SELECT gs.id, gs.course_id, gs.created_by, gs.created_at
FROM grade_schemes gs
JOIN courses c ON gs.course_id = c.id
WHERE gs.course_id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) GetSchemeByCourse(ctx context.Context, courseID int64) (GradeScheme, error) {
	row := q.db.QueryRow(ctx, getSchemeByCourse, courseID)
	var i GradeScheme
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertGradeComponent = `-- name: InsertGradeComponent :one
INSERT INTO grade_components (scheme_id, parent_id, name, weight, source_type, auto_kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, scheme_id, parent_id, name, weight, source_type, auto_kind, created_at
`

type InsertGradeComponentParams struct {
	SchemeID   int64
	ParentID   pgtype.Int8
	Name       string
	Weight     pgtype.Numeric
	SourceType pgtype.Text
	AutoKind   pgtype.Text
}

func (q *Queries) InsertGradeComponent(ctx context.Context, arg InsertGradeComponentParams) (GradeComponent, error) {
	row := q.db.QueryRow(ctx, insertGradeComponent,
		arg.SchemeID,
		arg.ParentID,
		arg.Name,
		arg.Weight,
		arg.SourceType,
		arg.AutoKind,
	)
	var i GradeComponent
	err := row.Scan(
		&i.ID,
		&i.SchemeID,
		&i.ParentID,
		&i.Name,
		&i.Weight,
		&i.SourceType,
		&i.AutoKind,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicationsForStudent = `-- name: ListPublicationsForStudent :many
SELECT p.id, p.component_id, p.student_id, p.value, p.published_at
FROM grade_publications p
JOIN grade_components c ON p.component_id = c.id
JOIN grade_schemes s ON c.scheme_id = s.id
WHERE s.course_id = $1 AND p.student_id = $2 AND c.parent_id IS NULL
`

type ListPublicationsForStudentParams struct {
	CourseID  int64
	StudentID int64
}

func (q *Queries) ListPublicationsForStudent(ctx context.Context, arg ListPublicationsForStudentParams) ([]GradePublication, error) {
	rows, err := q.db.Query(ctx, listPublicationsForStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradePublication
	for rows.Next() {
		var i GradePublication
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.StudentID,
			&i.Value,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemeComponents = `-- name: ListSchemeComponents :many
SELECT gc.id, gc.scheme_id, gc.parent_id, gc.name, gc.weight, gc.source_type, gc.auto_kind, gc.created_at
FROM grade_components gc
JOIN grade_schemes gs ON gc.scheme_id = gs.id
WHERE gs.course_id = $1
ORDER BY gc.parent_id NULLS FIRST, gc.id
`

func (q *Queries) ListSchemeComponents(ctx context.Context, courseID int64) ([]GradeComponent, error) {
	rows, err := q.db.Query(ctx, listSchemeComponents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradeComponent
	for rows.Next() {
		var i GradeComponent
		if err := rows.Scan(
			&i.ID,
			&i.SchemeID,
			&i.ParentID,
			&i.Name,
			&i.Weight,
			&i.SourceType,
			&i.AutoKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoresForStudent = `-- name: ListScoresForStudent :many
SELECT s.id, s.component_id, s.student_id, s.score, s.updated_at
FROM grade_scores s
JOIN grade_components c ON s.component_id = c.id
JOIN grade_schemes gs ON c.scheme_id = gs.id
WHERE gs.course_id = $1 AND s.student_id = $2
`

type ListScoresForStudentParams struct {
	CourseID  int64
	StudentID int64
}

func (q *Queries) ListScoresForStudent(ctx context.Context, arg ListScoresForStudentParams) ([]GradeScore, error) {
	rows, err := q.db.Query(ctx, listScoresForStudent, arg.CourseID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GradeScore
	for rows.Next() {
		var i GradeScore
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.StudentID,
			&i.Score,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGradePublication = `-- name: UpsertGradePublication :exec
INSERT INTO grade_publications (component_id, student_id, value, published_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (component_id, student_id)
DO UPDATE SET value = EXCLUDED.value, published_at = now()
`

type UpsertGradePublicationParams struct {
	ComponentID int64
	StudentID   int64
	Value       pgtype.Numeric
}

func (q *Queries) UpsertGradePublication(ctx context.Context, arg UpsertGradePublicationParams) error {
	_, err := q.db.Exec(ctx, upsertGradePublication, arg.ComponentID, arg.StudentID, arg.Value)
	return err
}

const upsertGradeScore = `-- name: UpsertGradeScore :exec
INSERT INTO grade_scores (component_id, student_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (component_id, student_id)
DO UPDATE SET score = EXCLUDED.score, updated_at = now()
`

type UpsertGradeScoreParams struct {
	ComponentID int64
	StudentID   int64
	Score       pgtype.Numeric
}

func (q *Queries) UpsertGradeScore(ctx context.Context, arg UpsertGradeScoreParams) error {
	_, err := q.db.Exec(ctx, upsertGradeScore, arg.ComponentID, arg.StudentID, arg.Score)
	return err
}
