// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: healthcheck.sql

package db

import (
	"context"
)

const healthCountUsers = `-- name: HealthCountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) HealthCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, healthCountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
