// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleStudent  UserRole = "student"
	UserRoleLecturer UserRole = "lecturer"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Assignment struct {
	ID                int64
	CourseID          int64
	Title             string
	Description       pgtype.Text
	Deadline          pgtype.Timestamptz
	AcceptLate        bool
	LateThresholdDays pgtype.Int4
	CreatedBy         int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AuditLog struct {
	ID            int64
	ActorID       pgtype.Int8
	Action        string
	Target        pgtype.Text
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	TargetType    pgtype.Text
	TargetID      pgtype.Int8
	OperationID   pgtype.UUID
	AffectedCount pgtype.Int4
}

type Course struct {
	ID        int64
	Code      string
	Name      string
	Term      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CourseLecturer struct {
	ID         int64
	CourseID   int64
	LecturerID int64
	CreatedAt  pgtype.Timestamptz
}

type Notification struct {
	ID           int64
	RecipientID  int64
	Type         string
	Title        string
	Body         string
	ResourceType pgtype.Text
	ResourceID   pgtype.Int8
	Link         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ReadAt       pgtype.Timestamptz
}

type Quiz struct {
	ID           int64
	CourseID     int64
	Title        string
	PoolSize     pgtype.Int4
	MaxQuestions pgtype.Int4
	MaxGrade     pgtype.Numeric
	Shuffle      pgtype.Bool
	RetakeCount  pgtype.Int4
	OpenAt       pgtype.Timestamptz
	CloseAt      pgtype.Timestamptz
	CreatedBy    int64
	CreatedAt    pgtype.Timestamptz
}

type QuizAttempt struct {
	ID            int64
	QuizID        int64
	StudentID     int64
	AttemptNumber pgtype.Int4
	Status        string
	Score         pgtype.Numeric
	StartedAt     pgtype.Timestamptz
	SubmittedAt   pgtype.Timestamptz
}

type QuizAttemptAnswer struct {
	ID                int64
	AttemptID         int64
	QuestionID        int64
	SelectedOptionIds []int64
	CreatedAt         pgtype.Timestamptz
}

type QuizQuestion struct {
	ID           int64
	QuizID       int64
	Prompt       pgtype.Text
	QuestionType string
	CreatedAt    pgtype.Timestamptz
}

type QuizQuestionOption struct {
	ID         int64
	QuestionID int64
	Text       pgtype.Text
	IsCorrect  bool
	CreatedAt  pgtype.Timestamptz
}

type StudentEnrollment struct {
	ID        int64
	CourseID  int64
	StudentID int64
	CreatedAt pgtype.Timestamptz
}

type Submission struct {
	ID                 int64
	AssignmentID       int64
	StudentID          int64
	Version            int32
	CloudinaryPublicID string
	CloudinaryFormat   string
	OriginalFilename   string
	IsLate             bool
	SubmittedAt        pgtype.Timestamptz
	Score              pgtype.Numeric
	Feedback           pgtype.Text
	GradedAt           pgtype.Timestamptz
	GradedBy           pgtype.Int8
}

type User struct {
	ID                 int64
	Username           string
	PasswordHash       string
	Role               UserRole
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	PasswordChangedAt  pgtype.Timestamptz
	FullName           pgtype.Text
	DateOfBirth        pgtype.Date
	IsSystem           bool
}
