// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleStudent  UserRole = "student"
	UserRoleLecturer UserRole = "lecturer"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID            int64
	ActorID       pgtype.Int8
	Action        string
	Target        pgtype.Text
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	TargetType    pgtype.Text
	TargetID      pgtype.Int8
	OperationID   pgtype.UUID
	AffectedCount pgtype.Int4
}

type Course struct {
	ID        int64
	Code      string
	Name      string
	Term      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CourseLecturer struct {
	ID         int64
	CourseID   int64
	LecturerID int64
	CreatedAt  pgtype.Timestamptz
}

type StudentEnrollment struct {
	ID        int64
	CourseID  int64
	StudentID int64
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 int64
	Username           string
	PasswordHash       string
	Role               UserRole
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	PasswordChangedAt  pgtype.Timestamptz
	FullName           pgtype.Text
	DateOfBirth        pgtype.Date
	IsSystem           bool
}
