// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notifications
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, recipientID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    recipient_id, type, title, body, resource_type, resource_id, link
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, recipient_id, type, title, body, resource_type, resource_id, link, created_at, read_at
`

type InsertNotificationParams struct {
	RecipientID  int64
	Type         string
	Title        string
	Body         string
	ResourceType pgtype.Text
	ResourceID   pgtype.Int8
	Link         pgtype.Text
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.RecipientID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.ResourceType,
		arg.ResourceID,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ResourceType,
		&i.ResourceID,
		&i.Link,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_id, type, title, body, resource_type, resource_id, link, created_at, read_at FROM notifications
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	RecipientID int64
	Limit       int32
	Offset      int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ResourceType,
			&i.ResourceID,
			&i.Link,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :execrows
UPDATE notifications
SET read_at = now()
WHERE id = $1 AND recipient_id = $2 AND read_at IS NULL
`

type MarkReadParams struct {
	ID          int64
	RecipientID int64
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
