// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizQuestions = `-- name: CountQuizQuestions :one
SELECT count(*) FROM quiz_questions
WHERE quiz_id = $1
`

func (q *Queries) CountQuizQuestions(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countQuizQuestions, quizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertOption = `-- name: InsertOption :one
INSERT INTO quiz_question_options (
    question_id, text, is_correct
) VALUES (
    $1, $2, $3
) RETURNING id, question_id, text, is_correct, created_at
`

type InsertOptionParams struct {
	QuestionID int64
	Text       pgtype.Text
	IsCorrect  bool
}

func (q *Queries) InsertOption(ctx context.Context, arg InsertOptionParams) (QuizQuestionOption, error) {
	row := q.db.QueryRow(ctx, insertOption, arg.QuestionID, arg.Text, arg.IsCorrect)
	var i QuizQuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO quiz_questions (
    quiz_id, prompt, question_type
) VALUES (
    $1, $2, $3
) RETURNING id, quiz_id, prompt, question_type, created_at
`

type InsertQuestionParams struct {
	QuizID       int64
	Prompt       pgtype.Text
	QuestionType string
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, insertQuestion, arg.QuizID, arg.Prompt, arg.QuestionType)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Prompt,
		&i.QuestionType,
		&i.CreatedAt,
	)
	return i, err
}

const listOptionsForQuestion = `-- name: ListOptionsForQuestion :many
SELECT id, question_id, text, is_correct, created_at FROM quiz_question_options
WHERE question_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOptionsForQuestion(ctx context.Context, questionID int64) ([]QuizQuestionOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestionOption
	for rows.Next() {
		var i QuizQuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsForQuiz = `-- name: ListOptionsForQuiz :many
SELECT o.id, o.question_id, o.text, o.is_correct, o.created_at FROM quiz_question_options o
JOIN quiz_questions q ON o.question_id = q.id
WHERE q.quiz_id = $1
ORDER BY o.id ASC
`

func (q *Queries) ListOptionsForQuiz(ctx context.Context, quizID int64) ([]QuizQuestionOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestionOption
	for rows.Next() {
		var i QuizQuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsForQuiz = `-- name: ListQuestionsForQuiz :many
SELECT id, quiz_id, prompt, question_type, created_at FROM quiz_questions
WHERE quiz_id = $1
ORDER BY id ASC
`

func (q *Queries) ListQuestionsForQuiz(ctx context.Context, quizID int64) ([]QuizQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsForQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestion
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Prompt,
			&i.QuestionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
