// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttempts = `-- name: CountAttempts :one
SELECT count(*) FROM quiz_attempts
WHERE quiz_id = $1 AND student_id = $2
`

type CountAttemptsParams struct {
	QuizID    int64
	StudentID int64
}

func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttempts, arg.QuizID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, quiz_id, student_id, attempt_number, status, score, started_at, submitted_at FROM quiz_attempts
WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id int64) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.Score,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getInProgressAttempt = `-- name: GetInProgressAttempt :one
SELECT id, quiz_id, student_id, attempt_number, status, score, started_at, submitted_at FROM quiz_attempts
WHERE quiz_id = $1 AND student_id = $2 AND status = 'IN_PROGRESS'
`

type GetInProgressAttemptParams struct {
	QuizID    int64
	StudentID int64
}

func (q *Queries) GetInProgressAttempt(ctx context.Context, arg GetInProgressAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getInProgressAttempt, arg.QuizID, arg.StudentID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.Score,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getMaxScore = `-- name: GetMaxScore :one
SELECT COALESCE(MAX(score), 0)::numeric AS max_score
FROM quiz_attempts
WHERE quiz_id = $1 AND student_id = $2 AND status IN ('SUBMITTED', 'AUTO_SUBMITTED')
`

type GetMaxScoreParams struct {
	QuizID    int64
	StudentID int64
}

func (q *Queries) GetMaxScore(ctx context.Context, arg GetMaxScoreParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getMaxScore, arg.QuizID, arg.StudentID)
	var max_score pgtype.Numeric
	err := row.Scan(&max_score)
	return max_score, err
}

const insertAttemptAnswer = `-- name: InsertAttemptAnswer :exec
INSERT INTO quiz_attempt_answers (
    attempt_id, question_id, selected_option_ids
) VALUES (
    $1, $2, $3
)
`

type InsertAttemptAnswerParams struct {
	AttemptID         int64
	QuestionID        int64
	SelectedOptionIds []int64
}

func (q *Queries) InsertAttemptAnswer(ctx context.Context, arg InsertAttemptAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAttemptAnswer, arg.AttemptID, arg.QuestionID, arg.SelectedOptionIds)
	return err
}

const listAttemptAnswers = `-- name: ListAttemptAnswers :many
SELECT id, attempt_id, question_id, selected_option_ids, created_at FROM quiz_attempt_answers
WHERE attempt_id = $1
`

func (q *Queries) ListAttemptAnswers(ctx context.Context, attemptID int64) ([]QuizAttemptAnswer, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswers, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttemptAnswer
	for rows.Next() {
		var i QuizAttemptAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedOptionIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttemptAutoSubmitted = `-- name: MarkAttemptAutoSubmitted :execrows
UPDATE quiz_attempts
SET status = 'AUTO_SUBMITTED', score = $2, submitted_at = $3
WHERE id = $1 AND status = 'IN_PROGRESS'
`

type MarkAttemptAutoSubmittedParams struct {
	ID          int64
	Score       pgtype.Numeric
	SubmittedAt pgtype.Timestamptz
}

func (q *Queries) MarkAttemptAutoSubmitted(ctx context.Context, arg MarkAttemptAutoSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAttemptAutoSubmitted, arg.ID, arg.Score, arg.SubmittedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAttemptSubmitted = `-- name: MarkAttemptSubmitted :execrows
UPDATE quiz_attempts
SET status = 'SUBMITTED', score = $2, submitted_at = now()
WHERE id = $1 AND status = 'IN_PROGRESS'
`

type MarkAttemptSubmittedParams struct {
	ID    int64
	Score pgtype.Numeric
}

func (q *Queries) MarkAttemptSubmitted(ctx context.Context, arg MarkAttemptSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAttemptSubmitted, arg.ID, arg.Score)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startAttempt = `-- name: StartAttempt :one
INSERT INTO quiz_attempts (
    quiz_id, student_id, status, attempt_number
) VALUES (
    $1, $2, 'IN_PROGRESS', $3
) RETURNING id, quiz_id, student_id, attempt_number, status, score, started_at, submitted_at
`

type StartAttemptParams struct {
	QuizID        int64
	StudentID     int64
	AttemptNumber pgtype.Int4
}

func (q *Queries) StartAttempt(ctx context.Context, arg StartAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, startAttempt, arg.QuizID, arg.StudentID, arg.AttemptNumber)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.Score,
		&i.StartedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const updateAttemptAnswer = `-- name: UpdateAttemptAnswer :exec
UPDATE quiz_attempt_answers
SET selected_option_ids = $3
WHERE attempt_id = $1 AND question_id = $2
`

type UpdateAttemptAnswerParams struct {
	AttemptID         int64
	QuestionID        int64
	SelectedOptionIds []int64
}

func (q *Queries) UpdateAttemptAnswer(ctx context.Context, arg UpdateAttemptAnswerParams) error {
	_, err := q.db.Exec(ctx, updateAttemptAnswer, arg.AttemptID, arg.QuestionID, arg.SelectedOptionIds)
	return err
}
