// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (
    course_id, title, pool_size, max_questions, max_grade,
    shuffle, retake_count, open_at, close_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, course_id, title, pool_size, max_questions, max_grade, shuffle, retake_count, open_at, close_at, created_by, created_at
`

type CreateQuizParams struct {
	CourseID     int64
	Title        string
	PoolSize     pgtype.Int4
	MaxQuestions pgtype.Int4
	MaxGrade     pgtype.Numeric
	Shuffle      pgtype.Bool
	RetakeCount  pgtype.Int4
	OpenAt       pgtype.Timestamptz
	CloseAt      pgtype.Timestamptz
	CreatedBy    int64
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.CourseID,
		arg.Title,
		arg.PoolSize,
		arg.MaxQuestions,
		arg.MaxGrade,
		arg.Shuffle,
		arg.RetakeCount,
		arg.OpenAt,
		arg.CloseAt,
		arg.CreatedBy,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.PoolSize,
		&i.MaxQuestions,
		&i.MaxGrade,
		&i.Shuffle,
		&i.RetakeCount,
		&i.OpenAt,
		&i.CloseAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT q.id, q.course_id, q.title, q.pool_size, q.max_questions, q.max_grade, q.shuffle, q.retake_count, q.open_at, q.close_at, q.created_by, q.created_at
FROM quizzes q
JOIN courses c ON q.course_id = c.id
WHERE q.id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) GetQuizByID(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.PoolSize,
		&i.MaxQuestions,
		&i.MaxGrade,
		&i.Shuffle,
		&i.RetakeCount,
		&i.OpenAt,
		&i.CloseAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseQuizzes = `-- name: ListCourseQuizzes :many
SELECT q.id, q.course_id, q.title, q.pool_size, q.max_questions, q.max_grade, q.shuffle, q.retake_count, q.open_at, q.close_at, q.created_by, q.created_at
FROM quizzes q
JOIN courses c ON q.course_id = c.id
WHERE q.course_id = $1 AND c.deleted_at IS NULL
ORDER BY q.created_at DESC
`

func (q *Queries) ListCourseQuizzes(ctx context.Context, courseID int64) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listCourseQuizzes, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.PoolSize,
			&i.MaxQuestions,
			&i.MaxGrade,
			&i.Shuffle,
			&i.RetakeCount,
			&i.OpenAt,
			&i.CloseAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
