// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, course_id, student_id, targeted_lecturer_id, type, title, body, status, reply_note, replied_at, created_at
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id int64) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.TargetedLecturerID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.ReplyNote,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRequest = `-- name: InsertRequest :one
INSERT INTO requests (course_id, student_id, targeted_lecturer_id, type, title, body, status)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING')
RETURNING id, course_id, student_id, targeted_lecturer_id, type, title, body, status, reply_note, replied_at, created_at
`

type InsertRequestParams struct {
	CourseID           int64
	StudentID          int64
	TargetedLecturerID int64
	Type               string
	Title              string
	Body               string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.CourseID,
		arg.StudentID,
		arg.TargetedLecturerID,
		arg.Type,
		arg.Title,
		arg.Body,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.TargetedLecturerID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.ReplyNote,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLecturerRequests = `-- name: ListLecturerRequests :many
SELECT id, course_id, student_id, targeted_lecturer_id, type, title, body, status, reply_note, replied_at, created_at
FROM requests
WHERE targeted_lecturer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLecturerRequests(ctx context.Context, targetedLecturerID int64) ([]Request, error) {
	rows, err := q.db.Query(ctx, listLecturerRequests, targetedLecturerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.StudentID,
			&i.TargetedLecturerID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.ReplyNote,
			&i.RepliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentRequests = `-- name: ListStudentRequests :many
SELECT id, course_id, student_id, targeted_lecturer_id, type, title, body, status, reply_note, replied_at, created_at
FROM requests
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStudentRequests(ctx context.Context, studentID int64) ([]Request, error) {
	rows, err := q.db.Query(ctx, listStudentRequests, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.StudentID,
			&i.TargetedLecturerID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.ReplyNote,
			&i.RepliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyRequest = `-- name: ReplyRequest :one
UPDATE requests
SET status = $3,
    reply_note = $4,
    replied_at = now()
WHERE id = $1
  AND targeted_lecturer_id = $2
  AND status = 'PENDING'
RETURNING id, course_id, student_id, targeted_lecturer_id, type, title, body, status, reply_note, replied_at, created_at
`

type ReplyRequestParams struct {
	ID                 int64
	TargetedLecturerID int64
	Status             string
	ReplyNote          pgtype.Text
}

func (q *Queries) ReplyRequest(ctx context.Context, arg ReplyRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, replyRequest,
		arg.ID,
		arg.TargetedLecturerID,
		arg.Status,
		arg.ReplyNote,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.TargetedLecturerID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.ReplyNote,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}
