// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"
)

const getActiveSubmission = `-- name: GetActiveSubmission :one
SELECT id, assignment_id, student_id, version, cloudinary_public_id, cloudinary_format, original_filename, is_late, submitted_at, score, feedback, graded_at, graded_by
FROM submissions
WHERE assignment_id = $1 AND student_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetActiveSubmissionParams struct {
	AssignmentID int64
	StudentID    int64
}

func (q *Queries) GetActiveSubmission(ctx context.Context, arg GetActiveSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getActiveSubmission, arg.AssignmentID, arg.StudentID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Version,
		&i.CloudinaryPublicID,
		&i.CloudinaryFormat,
		&i.OriginalFilename,
		&i.IsLate,
		&i.SubmittedAt,
		&i.Score,
		&i.Feedback,
		&i.GradedAt,
		&i.GradedBy,
	)
	return i, err
}

const getMaxSubmissionVersion = `-- name: GetMaxSubmissionVersion :one
SELECT COALESCE(MAX(version), 0)::INT
FROM submissions
WHERE assignment_id = $1 AND student_id = $2
`

type GetMaxSubmissionVersionParams struct {
	AssignmentID int64
	StudentID    int64
}

func (q *Queries) GetMaxSubmissionVersion(ctx context.Context, arg GetMaxSubmissionVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSubmissionVersion, arg.AssignmentID, arg.StudentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT s.id, s.assignment_id, s.student_id, s.version, s.cloudinary_public_id, s.cloudinary_format, s.original_filename, s.is_late, s.submitted_at, s.score, s.feedback, s.graded_at, s.graded_by
FROM submissions s
JOIN assignments a ON s.assignment_id = a.id
JOIN courses c ON a.course_id = c.id
WHERE s.id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Version,
		&i.CloudinaryPublicID,
		&i.CloudinaryFormat,
		&i.OriginalFilename,
		&i.IsLate,
		&i.SubmittedAt,
		&i.Score,
		&i.Feedback,
		&i.GradedAt,
		&i.GradedBy,
	)
	return i, err
}

const insertSubmissionVersion = `-- name: InsertSubmissionVersion :one
INSERT INTO submissions (
    assignment_id, student_id, version, cloudinary_public_id, cloudinary_format,
    original_filename, is_late
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, assignment_id, student_id, version, cloudinary_public_id, cloudinary_format, original_filename, is_late, submitted_at, score, feedback, graded_at, graded_by
`

type InsertSubmissionVersionParams struct {
	AssignmentID       int64
	StudentID          int64
	Version            int32
	CloudinaryPublicID string
	CloudinaryFormat   string
	OriginalFilename   string
	IsLate             bool
}

func (q *Queries) InsertSubmissionVersion(ctx context.Context, arg InsertSubmissionVersionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, insertSubmissionVersion,
		arg.AssignmentID,
		arg.StudentID,
		arg.Version,
		arg.CloudinaryPublicID,
		arg.CloudinaryFormat,
		arg.OriginalFilename,
		arg.IsLate,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Version,
		&i.CloudinaryPublicID,
		&i.CloudinaryFormat,
		&i.OriginalFilename,
		&i.IsLate,
		&i.SubmittedAt,
		&i.Score,
		&i.Feedback,
		&i.GradedAt,
		&i.GradedBy,
	)
	return i, err
}

const listSubmissionVersions = `-- name: ListSubmissionVersions :many
SELECT id, assignment_id, student_id, version, cloudinary_public_id, cloudinary_format, original_filename, is_late, submitted_at, score, feedback, graded_at, graded_by
FROM submissions
WHERE assignment_id = $1 AND student_id = $2
ORDER BY version DESC
`

type ListSubmissionVersionsParams struct {
	AssignmentID int64
	StudentID    int64
}

func (q *Queries) ListSubmissionVersions(ctx context.Context, arg ListSubmissionVersionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionVersions, arg.AssignmentID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.Version,
			&i.CloudinaryPublicID,
			&i.CloudinaryFormat,
			&i.OriginalFilename,
			&i.IsLate,
			&i.SubmittedAt,
			&i.Score,
			&i.Feedback,
			&i.GradedAt,
			&i.GradedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
