// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, must_change_password, created_at, updated_at, deleted_at, password_changed_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, must_change_password, created_at, updated_at, deleted_at, password_changed_at FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const updatePasswordAndStamp = `-- name: UpdatePasswordAndStamp :exec
UPDATE users SET password_hash = $2, password_changed_at = now(), must_change_password = false, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePasswordAndStampParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdatePasswordAndStamp(ctx context.Context, arg UpdatePasswordAndStampParams) error {
	_, err := q.db.Exec(ctx, updatePasswordAndStamp, arg.ID, arg.PasswordHash)
	return err
}
